---
all user: com.citi.vdict.entity.view.AllUser
all table: com.citi.vdict.entity.view.AllTable
pack: com.citi.vdict.entity.view.Pack
pie: com.citi.vdict.entity.view.Pie
line chart: com.citi.vdict.entity.view.LineChart
chort: com.citi.vdict.entity.view.Chort
tree: com.citi.vdict.entity.view.Tree
cluster: com.citi.vdict.entity.view.Cluster
bundle: com.citi.vdict.entity.view.Bundle
histogram: com.citi.vdict.entity.view.Histogram
partition: com.citi.vdict.entity.view.Partition
...